project:
  type: website
  render:
    - "*.ipynb"

format:
  html:
    toc: true
    css: styles.css
    code-block-bg: true
    code-overflow: scroll
    code-line-numbers: false
    monofont: D2Coding
    language:
      crossref-tbl-title: "표"

website:
  title: "RedHat Book"
  sidebar:
    style: "docked"
    search: true
    contents:
      - "index.ipynb"
      - "user.ipynb"
      - "virtualbox.ipynb"
      - "package.ipynb"
      - "build.ipynb"
      - "systemd.ipynb"
